# Generated by Django 4.2.7 on 2023-12-03 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Имя агента', max_length=255, verbose_name='Агент')),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название очереди', max_length=255, verbose_name='Очередь')),
                ('skill', models.CharField(help_text='Название Умения', max_length=255, verbose_name='Умение')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='call_center.agent', verbose_name='Агент')),
            ],
        ),
        migrations.AddConstraint(
            model_name='queue',
            constraint=models.UniqueConstraint(fields=('name', 'agent'), name='unique_agent'),
        ),
    ]
