# Generated by Django 4.2.7 on 2023-12-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_center', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='mood',
            field=models.CharField(choices=[('happy', 'Летающий счастье'), ('sad', 'Мимолетная грусть'), ('excited', 'Буря эмоций'), ('calm', 'Спокойный океан'), ('angry', 'Ярость внутри'), ('confused', 'Загадочная путаница'), ('surprised', 'Неожиданный восторг'), ('content', 'Довольство моментом'), ('bored', 'Скучающая рутина'), ('grateful', 'Благодарность сердца'), ('hungry', 'Гастрономическое волнение')], default='hungry', max_length=50),
        ),
    ]
