# Generated by Django 4.2.7 on 2023-12-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_center', '0002_alter_queue_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(help_text='Имя агента', max_length=255, unique=True, verbose_name='Агент'),
        ),
    ]
